import { beforeEach, describe, expect, it } from "vitest"

import { clearGameSession } from "@/engine/session/game-session-store"
import {
  getLocationInventoryById,
  getPlayerTeamInventory,
  replaceInventoryByOwner,
} from "@/features/items/data/session-inventories"
import { Item, ItemCategory } from "@/features/items/types"
import { applySessionTrade } from "@/features/trade/data/session-trades"

const TEST_LOCATION_ID = "trade-test-location"

function buildCash(quantity: number) {
  return new Item({
    id: "test-currency",
    name: "A币-100元",
    category: ItemCategory.Currency,
    weight: 0.001,
    value: 100,
    quantity,
  })
}

function buildTool(quantity: number) {
  return new Item({
    id: "test-tool",
    name: "多功能工具包",
    category: ItemCategory.Tool,
    weight: 2.1,
    value: 140,
    quantity,
  })
}

function buildChangeCash(quantity: number) {
  return new Item({
    id: "test-change-currency",
    name: "A币-20元",
    category: ItemCategory.Currency,
    weight: 0.001,
    value: 20,
    quantity,
  })
}

function buildMedicine(quantity: number) {
  return new Item({
    id: "test-medicine",
    name: "止血注射剂",
    category: ItemCategory.Medicine,
    weight: 0.2,
    value: 58,
    quantity,
  })
}

describe("session trades", () => {
  beforeEach(() => {
    clearGameSession()
  })

  it("applies successful trade to both inventories", () => {
    replaceInventoryByOwner({ type: "player-team" }, [buildCash(3)])
    replaceInventoryByOwner({ type: "location", id: TEST_LOCATION_ID }, [buildTool(1)])

    const result = applySessionTrade({
      target: {
        type: "location",
        id: TEST_LOCATION_ID,
        name: "测试地点",
        kind: "settlement",
      },
      restrictions: {
        blockedBuyFromPlayer: [],
        blockedSellToPlayer: [],
      },
      playerOfferSelection: {
        "test-currency": 2,
      },
      targetOfferSelection: {
        "test-tool": 1,
      },
    })

    expect(result.ok).toBe(true)

    const playerInventory = getPlayerTeamInventory()
    const locationInventory = getLocationInventoryById(TEST_LOCATION_ID)
    const playerCash = playerInventory.find((item) => item.id === "test-currency")
    const playerTool = playerInventory.find((item) => item.id === "test-tool")
    const locationCash = locationInventory.find((item) => item.id === "test-currency")

    expect(playerCash?.quantity).toBe(1)
    expect(playerTool?.quantity).toBe(1)
    expect(locationCash?.quantity).toBe(2)
    expect(locationInventory.find((item) => item.id === "test-tool")).toBeUndefined()
  })

  it("keeps inventories unchanged when trade validation fails", () => {
    replaceInventoryByOwner({ type: "player-team" }, [buildCash(1)])
    replaceInventoryByOwner({ type: "location", id: TEST_LOCATION_ID }, [buildTool(2)])

    const result = applySessionTrade({
      target: {
        type: "location",
        id: TEST_LOCATION_ID,
        name: "测试地点",
        kind: "settlement",
      },
      restrictions: {
        blockedBuyFromPlayer: [],
        blockedSellToPlayer: [],
      },
      playerOfferSelection: {
        "test-currency": 1,
      },
      targetOfferSelection: {
        "test-tool": 2,
      },
    })

    expect(result.ok).toBe(false)
    expect(getPlayerTeamInventory().find((item) => item.id === "test-currency")?.quantity).toBe(1)
    expect(getLocationInventoryById(TEST_LOCATION_ID).find((item) => item.id === "test-tool")?.quantity).toBe(2)
  })

  it("applies auto currency change generated by settlement", () => {
    replaceInventoryByOwner({ type: "player-team" }, [buildCash(1)])
    replaceInventoryByOwner({ type: "location", id: TEST_LOCATION_ID }, [
      buildMedicine(1),
      buildChangeCash(1),
    ])

    const result = applySessionTrade({
      target: {
        type: "location",
        id: TEST_LOCATION_ID,
        name: "测试地点",
        kind: "settlement",
      },
      restrictions: {
        blockedBuyFromPlayer: [],
        blockedSellToPlayer: [],
      },
      playerOfferSelection: {
        "test-currency": 1,
      },
      targetOfferSelection: {
        "test-medicine": 1,
      },
    })

    expect(result.ok).toBe(true)

    if (!result.ok) {
      return
    }

    expect(result.autoPlayerCurrencyGiven).toEqual([])
    expect(result.autoPlayerCurrencyReceived).toEqual([
      { itemId: "test-change-currency", quantity: 1 },
    ])
    expect(result.settlementExact).toBe(false)
    expect(result.settlementDelta).toBe(22)

    const playerInventory = getPlayerTeamInventory()
    const locationInventory = getLocationInventoryById(TEST_LOCATION_ID)
    expect(playerInventory.find((item) => item.id === "test-medicine")?.quantity).toBe(1)
    expect(playerInventory.find((item) => item.id === "test-change-currency")?.quantity).toBe(1)
    expect(locationInventory.find((item) => item.id === "test-currency")?.quantity).toBe(1)
  })
})
